// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsqjfpowqahawehcunse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zcWpmcG93cWFoYXdlaGN1bnNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDcyNTUsImV4cCI6MjA2NzYyMzI1NX0.b7RRwV3ZY8pndXZstBgB2Nn1LAd2NGEsv745Egfr-PQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});